package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 10/06/2014 11:59:13 by Hibernate Tools 3.6.0

import java.util.Objects;

/**
 * Bairro generated by hbm2java
 */
public class Bairro  implements java.io.Serializable {


     private Long idbairro;
     private Jurisdicao jurisdicao;
     private String nome;

    public Bairro() {
    }

    public Bairro(Jurisdicao jurisdicao, String nome) {
       this.jurisdicao = jurisdicao;
       this.nome = nome;
    }
   
    public Long getIdbairro() {
        return this.idbairro;
    }
    
    public void setIdbairro(Long idbairro) {
        this.idbairro = idbairro;
    }
    public Jurisdicao getJurisdicao() {
        return this.jurisdicao;
    }
    
    public void setJurisdicao(Jurisdicao jurisdicao) {
        this.jurisdicao = jurisdicao;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public void validate() {
        if(nome == null || jurisdicao == null){
            throw new IllegalArgumentException("Nome and Jurisdição cannot be null");
        }
    }

    @Override
    public String toString() {
        return "Bairro{" + "idbairro=" + idbairro + ", jurisdicao=" + jurisdicao + ", nome=" + nome + '}';
    }
}


