package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 10/06/2014 11:59:13 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Long idcategoria;
     private String nome;
     private String cor;
     private Set<Viagem> viagems = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nome, String cor) {
        this.nome = nome;
        this.cor = cor;
    }
    public Categoria(String nome, String cor, Set<Viagem> viagems) {
       this.nome = nome;
       this.cor = cor;
       this.viagems = viagems;
    }
   
    public Long getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(Long idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public Set<Viagem> getViagems() {
        return this.viagems;
    }
    
    public void setViagems(Set<Viagem> viagems) {
        this.viagems = viagems;
    }

    public void validate() {
        if(nome == null || cor == null){
            throw new IllegalArgumentException("Nome and Cor cannot be null");
        }
    }

    @Override
    public String toString() {
        return "Categoria{" + "idcategoria=" + idcategoria + ", nome=" + nome
                + ", cor=" + cor + ", viagems=" + viagems + '}';
    }
}


