package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 10/06/2014 11:59:13 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private Long idcidade;
     private Inspetoria inspetoria;
     private String nome;
     private Set<Jurisdicao> jurisdicaos = new HashSet(0);
     private Set<Feriado> feriados = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(String nome) {
        this.nome = nome;
    }
    public Cidade(Inspetoria inspetoria, String nome, Set<Jurisdicao> jurisdicaos, Set<Feriado> feriados) {
       this.inspetoria = inspetoria;
       this.nome = nome;
       this.jurisdicaos = jurisdicaos;
       this.feriados = feriados;
    }
   
    public Long getIdcidade() {
        return this.idcidade;
    }
    
    public void setIdcidade(Long idcidade) {
        this.idcidade = idcidade;
    }
    public Inspetoria getInspetoria() {
        return this.inspetoria;
    }
    
    public void setInspetoria(Inspetoria inspetoria) {
        this.inspetoria = inspetoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Jurisdicao> getJurisdicaos() {
        return this.jurisdicaos;
    }
    
    public void setJurisdicaos(Set<Jurisdicao> jurisdicaos) {
        this.jurisdicaos = jurisdicaos;
    }
    public Set<Feriado> getFeriados() {
        return this.feriados;
    }
    
    public void setFeriados(Set<Feriado> feriados) {
        this.feriados = feriados;
    }

    public void validate() {
        if (nome == null) {
            throw new IllegalArgumentException("Nome cannot be null");
        }
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + Objects.hashCode(this.idcidade);
        hash = 59 * hash + Objects.hashCode(this.inspetoria);
        hash = 59 * hash + Objects.hashCode(this.nome);
        hash = 59 * hash + Objects.hashCode(this.jurisdicaos);
        hash = 59 * hash + Objects.hashCode(this.feriados);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Cidade other = (Cidade) obj;
        if (!Objects.equals(this.idcidade, other.idcidade)) {
            return false;
        }
        if (!Objects.equals(this.inspetoria, other.inspetoria)) {
            return false;
        }
        if (!Objects.equals(this.nome, other.nome)) {
            return false;
        }
        if (!Objects.equals(this.jurisdicaos, other.jurisdicaos)) {
            return false;
        }
        if (!Objects.equals(this.feriados, other.feriados)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Cidade{" + "idcidade=" + idcidade + ", inspetoria=" + inspetoria
                + ", nome=" + nome + ", jurisdicaos=" + jurisdicaos
                + ", feriados=" + feriados + '}';
    }
}


