package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 10/06/2014 11:59:13 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.Objects;

/**
 * Ferias generated by hbm2java
 */
public class Ferias  implements java.io.Serializable {


     private Long idferias;
     private Fiscal fiscal;
     private Date inicio;
     private Date fim;

    public Ferias() {
    }

    public Ferias(Fiscal fiscal, Date inicio, Date fim) {
       this.fiscal = fiscal;
       this.inicio = inicio;
       this.fim = fim;
    }
   
    public Long getIdferias() {
        return this.idferias;
    }
    
    public void setIdferias(Long idferias) {
        this.idferias = idferias;
    }
    public Fiscal getFiscal() {
        return this.fiscal;
    }
    
    public void setFiscal(Fiscal fiscal) {
        this.fiscal = fiscal;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFim() {
        return this.fim;
    }
    
    public void setFim(Date fim) {
        this.fim = fim;
    }

    public void validate() {
        if (fiscal == null || inicio == null || fim == null) {
            throw new IllegalArgumentException("Fiscal, Data Inicio and Data Fim"
                    + " cannot be null");
        }
    }

    @Override
    public String toString() {
        return "Ferias{" + "idferias=" + idferias + ", fiscal=" + fiscal
                + ", inicio=" + inicio + ", fim=" + fim + '}';
    }
}


