package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 10/06/2014 11:59:13 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Feriado generated by hbm2java
 */
public class Feriado  implements java.io.Serializable {


     private Long idferiado;
     private String nome;
     private Date data;
     private Boolean isFixo;
     private Set<Cidade> cidades = new HashSet(0);

    public Feriado() {
    }

	
    public Feriado(String nome, Date data, Boolean isFixo) {
        this.nome = nome;
        this.data = data;
        this.isFixo = isFixo;
    }
    public Feriado(String nome, Date data, Boolean isFixo, Set<Cidade> cidades) {
       this.nome = nome;
       this.data = data;
       this.isFixo = isFixo;
       this.cidades = cidades;
    }
   
    public Long getIdferiado() {
        return this.idferiado;
    }
    
    public void setIdferiado(Long idferiado) {
        this.idferiado = idferiado;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Boolean getIsFixo() {
        return this.isFixo;
    }
    
    public void setIsFixo(Boolean isFixo) {
        this.isFixo = isFixo;
    }
    public Set<Cidade> getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set<Cidade> cidades) {
        this.cidades = cidades;
    }

    public void validate() {
        if(nome == null || data == null || isFixo == null){
            throw new IllegalArgumentException("Nome, Data and IsFixo cannot be null");
        }
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 13 * hash + Objects.hashCode(this.idferiado);
        hash = 13 * hash + Objects.hashCode(this.nome);
        hash = 13 * hash + Objects.hashCode(this.data);
        hash = 13 * hash + Objects.hashCode(this.isFixo);
        hash = 13 * hash + Objects.hashCode(this.cidades);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Feriado other = (Feriado) obj;
        if (!Objects.equals(this.idferiado, other.idferiado)) {
            return false;
        }
        if (!Objects.equals(this.nome, other.nome)) {
            return false;
        }
        if (!Objects.equals(this.data, other.data)) {
            return false;
        }
        if (!Objects.equals(this.isFixo, other.isFixo)) {
            return false;
        }
        if (!Objects.equals(this.cidades, other.cidades)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Feriado{" + "idferiado=" + idferiado + ", nome=" + nome
                + ", data=" + data + ", isFixo=" + isFixo + ", cidades="
                + cidades + '}';
    }
}


