package creago.dfisc.afg.sifis.planejamento.entities;
// Generated 10/06/2014 11:59:13 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Rota generated by hbm2java
 */
public class Rota implements java.io.Serializable {

    private Long idrota;
    private Inspetoria inspetoria;
    private String nome;
    private Integer quilometragem;
    private Integer diaria;
    private Integer almoco;
    private Integer criterioRevisita;
    private Set<Viagem> viagems = new HashSet(0);
    private Set<Jurisdicao> jurisdicaos = new HashSet(0);

    public Rota() {
    }

    public Rota(Inspetoria inspetoria, String nome, Integer quilometragem, 
            Integer diaria, Integer almoco, Integer criterioRevisita) {
        this.inspetoria = inspetoria;
        this.nome = nome;
        this.quilometragem = quilometragem;
        this.diaria = diaria;
        this.almoco = almoco;
        this.criterioRevisita = criterioRevisita;
    }

    public Rota(Inspetoria inspetoria, String nome, Integer quilometragem,
            Integer diaria, Integer almoco, Integer criterioRevisita, Set<Viagem> viagems,
            Set<Jurisdicao> jurisdicaos) {
        this.inspetoria = inspetoria;
        this.nome = nome;
        this.quilometragem = quilometragem;
        this.diaria = diaria;
        this.almoco = almoco;
        this.criterioRevisita = criterioRevisita;
        this.viagems = viagems;
        this.jurisdicaos = jurisdicaos;
    }

    public Long getIdrota() {
        return this.idrota;
    }

    public void setIdrota(Long idrota) {
        this.idrota = idrota;
    }

    public Inspetoria getInspetoria() {
        return this.inspetoria;
    }

    public void setInspetoria(Inspetoria inspetoria) {
        this.inspetoria = inspetoria;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getQuilometragem() {
        return this.quilometragem;
    }

    public void setQuilometragem(Integer quilometragem) {
        this.quilometragem = quilometragem;
    }

    public Integer getDiaria() {
        return this.diaria;
    }

    public void setDiaria(Integer diaria) {
        this.diaria = diaria;
    }

    public Integer getAlmoco() {
        return this.almoco;
    }

    public void setAlmoco(Integer almoco) {
        this.almoco = almoco;
    }

    public Integer getCriterioRevisita() {
        return this.criterioRevisita;
    }

    public void setCriterioRevisita(Integer criterioRevisita) {
        this.criterioRevisita = criterioRevisita;
    }

    public Set<Viagem> getViagems() {
        return this.viagems;
    }

    public void setViagems(Set<Viagem> viagems) {
        this.viagems = viagems;
    }

    public Set<Jurisdicao> getJurisdicaos() {
        return this.jurisdicaos;
    }

    public void setJurisdicaos(Set<Jurisdicao> jurisdicaos) {
        this.jurisdicaos = jurisdicaos;
    }

    public void validate() {
        if (nome == null || inspetoria == null || quilometragem == null
                || diaria == null || almoco == null || criterioRevisita == null) {
            throw new IllegalArgumentException("Nome, Inspetoria, Quilometragem,"
                    + " Diária, Almoço and Critério de Revisita cannot be null");
        }
    }

    @Override
    public String toString() {
        return "Rota{" + "idrota=" + idrota + ", inspetoria=" + inspetoria
                + ", nome=" + nome + ", quilometragem=" + quilometragem
                + ", diaria=" + diaria + ", almoco=" + almoco + ", criterioRevisita="
                + criterioRevisita + ", viagems=" + viagems + ", jurisdicaos="
                + jurisdicaos + '}';
    }
    
}
